// Generated by rstantools.  Do not edit by hand.

/*
    plumstan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    plumstan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with plumstan.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_plumstan_model_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_plumstan_model");
    reader.add_event(159, 157, "end", "model_plumstan_model");
    return reader;
}
#include <stan_meta_header.hpp>
class model_plumstan_model : public prob_grad {
private:
        int data_chronology_n;
        int data_supported_n;
        int increments_n;
        std::vector<double> data_chronology_y;
        std::vector<double> data_chronology_y_sd;
        std::vector<double> data_supported_y;
        std::vector<double> data_supported_y_sd;
        std::vector<double> data_chronology_depth;
        std::vector<double> data_chronology_density;
        vector_d data_supported_density;
        std::vector<double> increments_thickness;
        std::vector<double> increments_depth_upper;
        std::vector<int> index_depth_increments_lower;
        std::vector<int> index_depth_increments_upper;
        double lambda;
        double prior_phi_alpha;
        double prior_phi_beta;
        double prior_omega_alpha;
        double prior_omega_beta;
        double prior_alpha_alpha;
        double prior_alpha_beta;
        double prior_data_supported_alpha;
        double prior_data_supported_beta;
public:
    model_plumstan_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_plumstan_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_plumstan_model_namespace::model_plumstan_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "data_chronology_n", "int", context__.to_vec());
            data_chronology_n = int(0);
            vals_i__ = context__.vals_i("data_chronology_n");
            pos__ = 0;
            data_chronology_n = vals_i__[pos__++];
            check_greater_or_equal(function__, "data_chronology_n", data_chronology_n, 1);
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "data_supported_n", "int", context__.to_vec());
            data_supported_n = int(0);
            vals_i__ = context__.vals_i("data_supported_n");
            pos__ = 0;
            data_supported_n = vals_i__[pos__++];
            check_greater_or_equal(function__, "data_supported_n", data_supported_n, 1);
            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "increments_n", "int", context__.to_vec());
            increments_n = int(0);
            vals_i__ = context__.vals_i("increments_n");
            pos__ = 0;
            increments_n = vals_i__[pos__++];
            check_greater_or_equal(function__, "increments_n", increments_n, 1);
            current_statement_begin__ = 13;
            validate_non_negative_index("data_chronology_y", "data_chronology_n", data_chronology_n);
            context__.validate_dims("data initialization", "data_chronology_y", "double", context__.to_vec(data_chronology_n));
            data_chronology_y = std::vector<double>(data_chronology_n, double(0));
            vals_r__ = context__.vals_r("data_chronology_y");
            pos__ = 0;
            size_t data_chronology_y_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < data_chronology_y_k_0_max__; ++k_0__) {
                data_chronology_y[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 14;
            validate_non_negative_index("data_chronology_y_sd", "data_chronology_n", data_chronology_n);
            context__.validate_dims("data initialization", "data_chronology_y_sd", "double", context__.to_vec(data_chronology_n));
            data_chronology_y_sd = std::vector<double>(data_chronology_n, double(0));
            vals_r__ = context__.vals_r("data_chronology_y_sd");
            pos__ = 0;
            size_t data_chronology_y_sd_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < data_chronology_y_sd_k_0_max__; ++k_0__) {
                data_chronology_y_sd[k_0__] = vals_r__[pos__++];
            }
            size_t data_chronology_y_sd_i_0_max__ = data_chronology_n;
            for (size_t i_0__ = 0; i_0__ < data_chronology_y_sd_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "data_chronology_y_sd[i_0__]", data_chronology_y_sd[i_0__], 0);
            }
            current_statement_begin__ = 15;
            validate_non_negative_index("data_supported_y", "data_supported_n", data_supported_n);
            context__.validate_dims("data initialization", "data_supported_y", "double", context__.to_vec(data_supported_n));
            data_supported_y = std::vector<double>(data_supported_n, double(0));
            vals_r__ = context__.vals_r("data_supported_y");
            pos__ = 0;
            size_t data_supported_y_k_0_max__ = data_supported_n;
            for (size_t k_0__ = 0; k_0__ < data_supported_y_k_0_max__; ++k_0__) {
                data_supported_y[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 16;
            validate_non_negative_index("data_supported_y_sd", "data_supported_n", data_supported_n);
            context__.validate_dims("data initialization", "data_supported_y_sd", "double", context__.to_vec(data_supported_n));
            data_supported_y_sd = std::vector<double>(data_supported_n, double(0));
            vals_r__ = context__.vals_r("data_supported_y_sd");
            pos__ = 0;
            size_t data_supported_y_sd_k_0_max__ = data_supported_n;
            for (size_t k_0__ = 0; k_0__ < data_supported_y_sd_k_0_max__; ++k_0__) {
                data_supported_y_sd[k_0__] = vals_r__[pos__++];
            }
            size_t data_supported_y_sd_i_0_max__ = data_supported_n;
            for (size_t i_0__ = 0; i_0__ < data_supported_y_sd_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "data_supported_y_sd[i_0__]", data_supported_y_sd[i_0__], 0);
            }
            current_statement_begin__ = 19;
            validate_non_negative_index("data_chronology_depth", "data_chronology_n", data_chronology_n);
            context__.validate_dims("data initialization", "data_chronology_depth", "double", context__.to_vec(data_chronology_n));
            data_chronology_depth = std::vector<double>(data_chronology_n, double(0));
            vals_r__ = context__.vals_r("data_chronology_depth");
            pos__ = 0;
            size_t data_chronology_depth_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < data_chronology_depth_k_0_max__; ++k_0__) {
                data_chronology_depth[k_0__] = vals_r__[pos__++];
            }
            size_t data_chronology_depth_i_0_max__ = data_chronology_n;
            for (size_t i_0__ = 0; i_0__ < data_chronology_depth_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "data_chronology_depth[i_0__]", data_chronology_depth[i_0__], 0);
            }
            current_statement_begin__ = 22;
            validate_non_negative_index("data_chronology_density", "data_chronology_n", data_chronology_n);
            context__.validate_dims("data initialization", "data_chronology_density", "double", context__.to_vec(data_chronology_n));
            data_chronology_density = std::vector<double>(data_chronology_n, double(0));
            vals_r__ = context__.vals_r("data_chronology_density");
            pos__ = 0;
            size_t data_chronology_density_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < data_chronology_density_k_0_max__; ++k_0__) {
                data_chronology_density[k_0__] = vals_r__[pos__++];
            }
            size_t data_chronology_density_i_0_max__ = data_chronology_n;
            for (size_t i_0__ = 0; i_0__ < data_chronology_density_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "data_chronology_density[i_0__]", data_chronology_density[i_0__], 0);
            }
            current_statement_begin__ = 23;
            validate_non_negative_index("data_supported_density", "data_supported_n", data_supported_n);
            context__.validate_dims("data initialization", "data_supported_density", "vector_d", context__.to_vec(data_supported_n));
            data_supported_density = Eigen::Matrix<double, Eigen::Dynamic, 1>(data_supported_n);
            vals_r__ = context__.vals_r("data_supported_density");
            pos__ = 0;
            size_t data_supported_density_j_1_max__ = data_supported_n;
            for (size_t j_1__ = 0; j_1__ < data_supported_density_j_1_max__; ++j_1__) {
                data_supported_density(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 26;
            validate_non_negative_index("increments_thickness", "increments_n", increments_n);
            context__.validate_dims("data initialization", "increments_thickness", "double", context__.to_vec(increments_n));
            increments_thickness = std::vector<double>(increments_n, double(0));
            vals_r__ = context__.vals_r("increments_thickness");
            pos__ = 0;
            size_t increments_thickness_k_0_max__ = increments_n;
            for (size_t k_0__ = 0; k_0__ < increments_thickness_k_0_max__; ++k_0__) {
                increments_thickness[k_0__] = vals_r__[pos__++];
            }
            size_t increments_thickness_i_0_max__ = increments_n;
            for (size_t i_0__ = 0; i_0__ < increments_thickness_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "increments_thickness[i_0__]", increments_thickness[i_0__], 0);
            }
            current_statement_begin__ = 27;
            validate_non_negative_index("increments_depth_upper", "increments_n", increments_n);
            context__.validate_dims("data initialization", "increments_depth_upper", "double", context__.to_vec(increments_n));
            increments_depth_upper = std::vector<double>(increments_n, double(0));
            vals_r__ = context__.vals_r("increments_depth_upper");
            pos__ = 0;
            size_t increments_depth_upper_k_0_max__ = increments_n;
            for (size_t k_0__ = 0; k_0__ < increments_depth_upper_k_0_max__; ++k_0__) {
                increments_depth_upper[k_0__] = vals_r__[pos__++];
            }
            size_t increments_depth_upper_i_0_max__ = increments_n;
            for (size_t i_0__ = 0; i_0__ < increments_depth_upper_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "increments_depth_upper[i_0__]", increments_depth_upper[i_0__], 0);
            }
            current_statement_begin__ = 30;
            validate_non_negative_index("index_depth_increments_lower", "data_chronology_n", data_chronology_n);
            context__.validate_dims("data initialization", "index_depth_increments_lower", "int", context__.to_vec(data_chronology_n));
            index_depth_increments_lower = std::vector<int>(data_chronology_n, int(0));
            vals_i__ = context__.vals_i("index_depth_increments_lower");
            pos__ = 0;
            size_t index_depth_increments_lower_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < index_depth_increments_lower_k_0_max__; ++k_0__) {
                index_depth_increments_lower[k_0__] = vals_i__[pos__++];
            }
            size_t index_depth_increments_lower_i_0_max__ = data_chronology_n;
            for (size_t i_0__ = 0; i_0__ < index_depth_increments_lower_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "index_depth_increments_lower[i_0__]", index_depth_increments_lower[i_0__], 1);
            }
            current_statement_begin__ = 33;
            validate_non_negative_index("index_depth_increments_upper", "data_chronology_n", data_chronology_n);
            context__.validate_dims("data initialization", "index_depth_increments_upper", "int", context__.to_vec(data_chronology_n));
            index_depth_increments_upper = std::vector<int>(data_chronology_n, int(0));
            vals_i__ = context__.vals_i("index_depth_increments_upper");
            pos__ = 0;
            size_t index_depth_increments_upper_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < index_depth_increments_upper_k_0_max__; ++k_0__) {
                index_depth_increments_upper[k_0__] = vals_i__[pos__++];
            }
            size_t index_depth_increments_upper_i_0_max__ = data_chronology_n;
            for (size_t i_0__ = 0; i_0__ < index_depth_increments_upper_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "index_depth_increments_upper[i_0__]", index_depth_increments_upper[i_0__], 1);
            }
            current_statement_begin__ = 36;
            context__.validate_dims("data initialization", "lambda", "double", context__.to_vec());
            lambda = double(0);
            vals_r__ = context__.vals_r("lambda");
            pos__ = 0;
            lambda = vals_r__[pos__++];
            current_statement_begin__ = 39;
            context__.validate_dims("data initialization", "prior_phi_alpha", "double", context__.to_vec());
            prior_phi_alpha = double(0);
            vals_r__ = context__.vals_r("prior_phi_alpha");
            pos__ = 0;
            prior_phi_alpha = vals_r__[pos__++];
            current_statement_begin__ = 40;
            context__.validate_dims("data initialization", "prior_phi_beta", "double", context__.to_vec());
            prior_phi_beta = double(0);
            vals_r__ = context__.vals_r("prior_phi_beta");
            pos__ = 0;
            prior_phi_beta = vals_r__[pos__++];
            current_statement_begin__ = 41;
            context__.validate_dims("data initialization", "prior_omega_alpha", "double", context__.to_vec());
            prior_omega_alpha = double(0);
            vals_r__ = context__.vals_r("prior_omega_alpha");
            pos__ = 0;
            prior_omega_alpha = vals_r__[pos__++];
            current_statement_begin__ = 42;
            context__.validate_dims("data initialization", "prior_omega_beta", "double", context__.to_vec());
            prior_omega_beta = double(0);
            vals_r__ = context__.vals_r("prior_omega_beta");
            pos__ = 0;
            prior_omega_beta = vals_r__[pos__++];
            current_statement_begin__ = 43;
            context__.validate_dims("data initialization", "prior_alpha_alpha", "double", context__.to_vec());
            prior_alpha_alpha = double(0);
            vals_r__ = context__.vals_r("prior_alpha_alpha");
            pos__ = 0;
            prior_alpha_alpha = vals_r__[pos__++];
            current_statement_begin__ = 44;
            context__.validate_dims("data initialization", "prior_alpha_beta", "double", context__.to_vec());
            prior_alpha_beta = double(0);
            vals_r__ = context__.vals_r("prior_alpha_beta");
            pos__ = 0;
            prior_alpha_beta = vals_r__[pos__++];
            current_statement_begin__ = 45;
            context__.validate_dims("data initialization", "prior_data_supported_alpha", "double", context__.to_vec());
            prior_data_supported_alpha = double(0);
            vals_r__ = context__.vals_r("prior_data_supported_alpha");
            pos__ = 0;
            prior_data_supported_alpha = vals_r__[pos__++];
            current_statement_begin__ = 46;
            context__.validate_dims("data initialization", "prior_data_supported_beta", "double", context__.to_vec());
            prior_data_supported_beta = double(0);
            vals_r__ = context__.vals_r("prior_data_supported_beta");
            pos__ = 0;
            prior_data_supported_beta = vals_r__[pos__++];
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 51;
            num_params_r__ += 1;
            current_statement_begin__ = 52;
            num_params_r__ += 1;
            current_statement_begin__ = 53;
            num_params_r__ += 1;
            current_statement_begin__ = 54;
            validate_non_negative_index("alpha", "increments_n", increments_n);
            num_params_r__ += (1 * increments_n);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_plumstan_model() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 51;
        if (!(context__.contains_r("phi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable phi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "phi", "double", context__.to_vec());
        double phi(0);
        phi = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, phi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable phi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 52;
        if (!(context__.contains_r("omega")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable omega missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("omega");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "omega", "double", context__.to_vec());
        double omega(0);
        omega = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, omega);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable omega: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 53;
        if (!(context__.contains_r("data_supported_alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable data_supported_alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("data_supported_alpha");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "data_supported_alpha", "double", context__.to_vec());
        double data_supported_alpha(0);
        data_supported_alpha = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(data_supported_alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable data_supported_alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 54;
        if (!(context__.contains_r("alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha");
        pos__ = 0U;
        validate_non_negative_index("alpha", "increments_n", increments_n);
        context__.validate_dims("parameter initialization", "alpha", "double", context__.to_vec(increments_n));
        std::vector<double> alpha(increments_n, double(0));
        size_t alpha_k_0_max__ = increments_n;
        for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
            alpha[k_0__] = vals_r__[pos__++];
        }
        size_t alpha_i_0_max__ = increments_n;
        for (size_t i_0__ = 0; i_0__ < alpha_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, alpha[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 51;
            local_scalar_t__ phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.scalar_lb_constrain(0, lp__);
            else
                phi = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 52;
            local_scalar_t__ omega;
            (void) omega;  // dummy to suppress unused var warning
            if (jacobian__)
                omega = in__.scalar_lub_constrain(0, 1, lp__);
            else
                omega = in__.scalar_lub_constrain(0, 1);
            current_statement_begin__ = 53;
            local_scalar_t__ data_supported_alpha;
            (void) data_supported_alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                data_supported_alpha = in__.scalar_constrain(lp__);
            else
                data_supported_alpha = in__.scalar_constrain();
            current_statement_begin__ = 54;
            std::vector<local_scalar_t__> alpha;
            size_t alpha_d_0_max__ = increments_n;
            alpha.reserve(alpha_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < alpha_d_0_max__; ++d_0__) {
                if (jacobian__)
                    alpha.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    alpha.push_back(in__.scalar_lb_constrain(0));
            }
            // transformed parameters
            current_statement_begin__ = 59;
            validate_non_negative_index("m", "increments_n", increments_n);
            std::vector<local_scalar_t__> m(increments_n, local_scalar_t__(0));
            stan::math::initialize(m, DUMMY_VAR__);
            stan::math::fill(m, DUMMY_VAR__);
            current_statement_begin__ = 60;
            validate_non_negative_index("p_tot", "data_chronology_n", data_chronology_n);
            std::vector<local_scalar_t__> p_tot(data_chronology_n, local_scalar_t__(0));
            stan::math::initialize(p_tot, DUMMY_VAR__);
            stan::math::fill(p_tot, DUMMY_VAR__);
            current_statement_begin__ = 61;
            validate_non_negative_index("t", "(data_chronology_n + 1)", (data_chronology_n + 1));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> t((data_chronology_n + 1));
            stan::math::initialize(t, DUMMY_VAR__);
            stan::math::fill(t, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 64;
            stan::model::assign(m, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        get_base1(alpha, 1, "alpha", 1), 
                        "assigning variable m");
            current_statement_begin__ = 65;
            for (int k = 2; k <= increments_n; ++k) {
                current_statement_begin__ = 66;
                stan::model::assign(m, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            ((omega * get_base1(m, (k - 1), "m", 1)) + ((1 - omega) * get_base1(alpha, k, "alpha", 1))), 
                            "assigning variable m");
            }
            current_statement_begin__ = 70;
            stan::model::assign(t, 
                        stan::model::cons_list(stan::model::index_uni((data_chronology_n + 1)), stan::model::nil_index_list()), 
                        0, 
                        "assigning variable t");
            current_statement_begin__ = 73;
            for (int i = 1; i <= data_chronology_n; ++i) {
                current_statement_begin__ = 76;
                if (as_bool(logical_eq(get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), increments_n))) {
                    current_statement_begin__ = 78;
                    stan::model::assign(t, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((get_base1(data_chronology_depth, i, "data_chronology_depth", 1) - get_base1(increments_depth_upper, get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), "increments_depth_upper", 1)) * get_base1(m, get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), "m", 1)), 
                                "assigning variable t");
                } else {
                    current_statement_begin__ = 82;
                    stan::model::assign(t, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (dot_product(stan::model::rvalue(m, stan::model::cons_list(stan::model::index_min_max((get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1) + 1), get_base1(index_depth_increments_upper, i, "index_depth_increments_upper", 1)), stan::model::nil_index_list()), "m"), stan::model::rvalue(increments_thickness, stan::model::cons_list(stan::model::index_min_max((get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1) + 1), get_base1(index_depth_increments_upper, i, "index_depth_increments_upper", 1)), stan::model::nil_index_list()), "increments_thickness")) + ((get_base1(data_chronology_depth, i, "data_chronology_depth", 1) - get_base1(increments_depth_upper, get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), "increments_depth_upper", 1)) * get_base1(m, get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), "m", 1))), 
                                "assigning variable t");
                }
            }
            current_statement_begin__ = 89;
            for (int i = 1; i <= data_chronology_n; ++i) {
                current_statement_begin__ = 91;
                stan::model::assign(p_tot, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            ((mean(multiply(data_supported_alpha, data_supported_density)) * 10) + ((phi / lambda) * (stan::math::exp((-(lambda) * get_base1(t, (i + 1), "t", 1))) - stan::math::exp((-(lambda) * get_base1(t, i, "t", 1)))))), 
                            "assigning variable p_tot");
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 59;
            size_t m_k_0_max__ = increments_n;
            for (size_t k_0__ = 0; k_0__ < m_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(m[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: m" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable m: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            size_t m_i_0_max__ = increments_n;
            for (size_t i_0__ = 0; i_0__ < m_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "m[i_0__]", m[i_0__], 0);
            }
            current_statement_begin__ = 60;
            size_t p_tot_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < p_tot_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(p_tot[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: p_tot" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable p_tot: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 61;
            size_t t_j_1_max__ = (data_chronology_n + 1);
            for (size_t j_1__ = 0; j_1__ < t_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(t(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: t" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable t: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            current_statement_begin__ = 101;
            lp_accum__.add(gamma_log<propto__>(phi, prior_phi_alpha, prior_phi_beta));
            current_statement_begin__ = 104;
            lp_accum__.add(gamma_log<propto__>(data_supported_alpha, prior_data_supported_alpha, prior_data_supported_beta));
            current_statement_begin__ = 107;
            lp_accum__.add(beta_log<propto__>(omega, prior_omega_alpha, prior_omega_beta));
            current_statement_begin__ = 110;
            lp_accum__.add(gamma_log<propto__>(alpha, prior_alpha_alpha, prior_alpha_beta));
            current_statement_begin__ = 113;
            lp_accum__.add(normal_log<propto__>(data_supported_y, data_supported_alpha, data_supported_y_sd));
            current_statement_begin__ = 114;
            lp_accum__.add(normal_log<propto__>(data_chronology_y, p_tot, data_chronology_y_sd));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("phi");
        names__.push_back("omega");
        names__.push_back("data_supported_alpha");
        names__.push_back("alpha");
        names__.push_back("m");
        names__.push_back("p_tot");
        names__.push_back("t");
        names__.push_back("p_tot_measured");
        names__.push_back("p_tot_artificial");
        names__.push_back("t_artificial");
        names__.push_back("log_lik");
        names__.push_back("dev");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(increments_n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(increments_n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(data_chronology_n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((data_chronology_n + 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(data_chronology_n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(increments_n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(increments_n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(data_chronology_n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_plumstan_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double phi = in__.scalar_lb_constrain(0);
        vars__.push_back(phi);
        double omega = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(omega);
        double data_supported_alpha = in__.scalar_constrain();
        vars__.push_back(data_supported_alpha);
        std::vector<double> alpha;
        size_t alpha_d_0_max__ = increments_n;
        alpha.reserve(alpha_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < alpha_d_0_max__; ++d_0__) {
            alpha.push_back(in__.scalar_lb_constrain(0));
        }
        size_t alpha_k_0_max__ = increments_n;
        for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
            vars__.push_back(alpha[k_0__]);
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 59;
            validate_non_negative_index("m", "increments_n", increments_n);
            std::vector<double> m(increments_n, double(0));
            stan::math::initialize(m, DUMMY_VAR__);
            stan::math::fill(m, DUMMY_VAR__);
            current_statement_begin__ = 60;
            validate_non_negative_index("p_tot", "data_chronology_n", data_chronology_n);
            std::vector<double> p_tot(data_chronology_n, double(0));
            stan::math::initialize(p_tot, DUMMY_VAR__);
            stan::math::fill(p_tot, DUMMY_VAR__);
            current_statement_begin__ = 61;
            validate_non_negative_index("t", "(data_chronology_n + 1)", (data_chronology_n + 1));
            Eigen::Matrix<double, Eigen::Dynamic, 1> t((data_chronology_n + 1));
            stan::math::initialize(t, DUMMY_VAR__);
            stan::math::fill(t, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 64;
            stan::model::assign(m, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        get_base1(alpha, 1, "alpha", 1), 
                        "assigning variable m");
            current_statement_begin__ = 65;
            for (int k = 2; k <= increments_n; ++k) {
                current_statement_begin__ = 66;
                stan::model::assign(m, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            ((omega * get_base1(m, (k - 1), "m", 1)) + ((1 - omega) * get_base1(alpha, k, "alpha", 1))), 
                            "assigning variable m");
            }
            current_statement_begin__ = 70;
            stan::model::assign(t, 
                        stan::model::cons_list(stan::model::index_uni((data_chronology_n + 1)), stan::model::nil_index_list()), 
                        0, 
                        "assigning variable t");
            current_statement_begin__ = 73;
            for (int i = 1; i <= data_chronology_n; ++i) {
                current_statement_begin__ = 76;
                if (as_bool(logical_eq(get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), increments_n))) {
                    current_statement_begin__ = 78;
                    stan::model::assign(t, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                ((get_base1(data_chronology_depth, i, "data_chronology_depth", 1) - get_base1(increments_depth_upper, get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), "increments_depth_upper", 1)) * get_base1(m, get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), "m", 1)), 
                                "assigning variable t");
                } else {
                    current_statement_begin__ = 82;
                    stan::model::assign(t, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (dot_product(stan::model::rvalue(m, stan::model::cons_list(stan::model::index_min_max((get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1) + 1), get_base1(index_depth_increments_upper, i, "index_depth_increments_upper", 1)), stan::model::nil_index_list()), "m"), stan::model::rvalue(increments_thickness, stan::model::cons_list(stan::model::index_min_max((get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1) + 1), get_base1(index_depth_increments_upper, i, "index_depth_increments_upper", 1)), stan::model::nil_index_list()), "increments_thickness")) + ((get_base1(data_chronology_depth, i, "data_chronology_depth", 1) - get_base1(increments_depth_upper, get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), "increments_depth_upper", 1)) * get_base1(m, get_base1(index_depth_increments_lower, i, "index_depth_increments_lower", 1), "m", 1))), 
                                "assigning variable t");
                }
            }
            current_statement_begin__ = 89;
            for (int i = 1; i <= data_chronology_n; ++i) {
                current_statement_begin__ = 91;
                stan::model::assign(p_tot, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            ((mean(multiply(data_supported_alpha, data_supported_density)) * 10) + ((phi / lambda) * (stan::math::exp((-(lambda) * get_base1(t, (i + 1), "t", 1))) - stan::math::exp((-(lambda) * get_base1(t, i, "t", 1)))))), 
                            "assigning variable p_tot");
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 59;
            size_t m_i_0_max__ = increments_n;
            for (size_t i_0__ = 0; i_0__ < m_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "m[i_0__]", m[i_0__], 0);
            }
            // write transformed parameters
            if (include_tparams__) {
                size_t m_k_0_max__ = increments_n;
                for (size_t k_0__ = 0; k_0__ < m_k_0_max__; ++k_0__) {
                    vars__.push_back(m[k_0__]);
                }
                size_t p_tot_k_0_max__ = data_chronology_n;
                for (size_t k_0__ = 0; k_0__ < p_tot_k_0_max__; ++k_0__) {
                    vars__.push_back(p_tot[k_0__]);
                }
                size_t t_j_1_max__ = (data_chronology_n + 1);
                for (size_t j_1__ = 0; j_1__ < t_j_1_max__; ++j_1__) {
                    vars__.push_back(t(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 120;
            validate_non_negative_index("p_tot_measured", "data_chronology_n", data_chronology_n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> p_tot_measured(data_chronology_n);
            stan::math::initialize(p_tot_measured, DUMMY_VAR__);
            stan::math::fill(p_tot_measured, DUMMY_VAR__);
            current_statement_begin__ = 123;
            validate_non_negative_index("p_tot_artificial", "increments_n", increments_n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> p_tot_artificial(increments_n);
            stan::math::initialize(p_tot_artificial, DUMMY_VAR__);
            stan::math::fill(p_tot_artificial, DUMMY_VAR__);
            current_statement_begin__ = 126;
            validate_non_negative_index("t_artificial", "increments_n", increments_n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> t_artificial(increments_n);
            stan::math::initialize(t_artificial, DUMMY_VAR__);
            stan::math::fill(t_artificial, DUMMY_VAR__);
            current_statement_begin__ = 129;
            validate_non_negative_index("log_lik", "data_chronology_n", data_chronology_n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(data_chronology_n);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            current_statement_begin__ = 132;
            double dev;
            (void) dev;  // dummy to suppress unused var warning
            stan::math::initialize(dev, DUMMY_VAR__);
            stan::math::fill(dev, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 133;
            stan::math::assign(dev, 0);
            current_statement_begin__ = 136;
            for (int n = 1; n <= data_chronology_n; ++n) {
                current_statement_begin__ = 137;
                stan::model::assign(p_tot_measured, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            normal_rng(get_base1(p_tot, n, "p_tot", 1), get_base1(data_chronology_y_sd, n, "data_chronology_y_sd", 1), base_rng__), 
                            "assigning variable p_tot_measured");
            }
            current_statement_begin__ = 141;
            for (int n = 1; n <= increments_n; ++n) {
                current_statement_begin__ = 142;
                stan::model::assign(p_tot_artificial, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            dot_product(stan::model::rvalue(m, stan::model::cons_list(stan::model::index_min_max(n, increments_n), stan::model::nil_index_list()), "m"), stan::model::rvalue(increments_thickness, stan::model::cons_list(stan::model::index_min_max(n, increments_n), stan::model::nil_index_list()), "increments_thickness")), 
                            "assigning variable p_tot_artificial");
            }
            current_statement_begin__ = 146;
            for (int n = 1; n <= increments_n; ++n) {
                current_statement_begin__ = 147;
                stan::model::assign(t_artificial, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            dot_product(stan::model::rvalue(m, stan::model::cons_list(stan::model::index_min_max(n, increments_n), stan::model::nil_index_list()), "m"), stan::model::rvalue(increments_thickness, stan::model::cons_list(stan::model::index_min_max(n, increments_n), stan::model::nil_index_list()), "increments_thickness")), 
                            "assigning variable t_artificial");
            }
            current_statement_begin__ = 151;
            stan::math::assign(dev, (dev + (-(2) * normal_cdf_log(data_chronology_y, p_tot, data_chronology_y_sd))));
            current_statement_begin__ = 154;
            for (int n = 1; n <= data_chronology_n; ++n) {
                current_statement_begin__ = 155;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            normal_log(get_base1(p_tot_measured, n, "p_tot_measured", 1), get_base1(p_tot, n, "p_tot", 1), get_base1(data_chronology_y_sd, n, "data_chronology_y_sd", 1)), 
                            "assigning variable log_lik");
            }
            // validate, write generated quantities
            current_statement_begin__ = 120;
            size_t p_tot_measured_j_1_max__ = data_chronology_n;
            for (size_t j_1__ = 0; j_1__ < p_tot_measured_j_1_max__; ++j_1__) {
                vars__.push_back(p_tot_measured(j_1__));
            }
            current_statement_begin__ = 123;
            size_t p_tot_artificial_j_1_max__ = increments_n;
            for (size_t j_1__ = 0; j_1__ < p_tot_artificial_j_1_max__; ++j_1__) {
                vars__.push_back(p_tot_artificial(j_1__));
            }
            current_statement_begin__ = 126;
            size_t t_artificial_j_1_max__ = increments_n;
            for (size_t j_1__ = 0; j_1__ < t_artificial_j_1_max__; ++j_1__) {
                vars__.push_back(t_artificial(j_1__));
            }
            current_statement_begin__ = 129;
            size_t log_lik_j_1_max__ = data_chronology_n;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
            current_statement_begin__ = 132;
            vars__.push_back(dev);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_plumstan_model";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "omega";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "data_supported_alpha";
        param_names__.push_back(param_name_stream__.str());
        size_t alpha_k_0_max__ = increments_n;
        for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t m_k_0_max__ = increments_n;
            for (size_t k_0__ = 0; k_0__ < m_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "m" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t p_tot_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < p_tot_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p_tot" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t t_j_1_max__ = (data_chronology_n + 1);
            for (size_t j_1__ = 0; j_1__ < t_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "t" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t p_tot_measured_j_1_max__ = data_chronology_n;
        for (size_t j_1__ = 0; j_1__ < p_tot_measured_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p_tot_measured" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t p_tot_artificial_j_1_max__ = increments_n;
        for (size_t j_1__ = 0; j_1__ < p_tot_artificial_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p_tot_artificial" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t t_artificial_j_1_max__ = increments_n;
        for (size_t j_1__ = 0; j_1__ < t_artificial_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "t_artificial" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = data_chronology_n;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "dev";
        param_names__.push_back(param_name_stream__.str());
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "omega";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "data_supported_alpha";
        param_names__.push_back(param_name_stream__.str());
        size_t alpha_k_0_max__ = increments_n;
        for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t m_k_0_max__ = increments_n;
            for (size_t k_0__ = 0; k_0__ < m_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "m" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t p_tot_k_0_max__ = data_chronology_n;
            for (size_t k_0__ = 0; k_0__ < p_tot_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p_tot" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t t_j_1_max__ = (data_chronology_n + 1);
            for (size_t j_1__ = 0; j_1__ < t_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "t" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t p_tot_measured_j_1_max__ = data_chronology_n;
        for (size_t j_1__ = 0; j_1__ < p_tot_measured_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p_tot_measured" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t p_tot_artificial_j_1_max__ = increments_n;
        for (size_t j_1__ = 0; j_1__ < p_tot_artificial_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "p_tot_artificial" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t t_artificial_j_1_max__ = increments_n;
        for (size_t j_1__ = 0; j_1__ < t_artificial_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "t_artificial" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = data_chronology_n;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "dev";
        param_names__.push_back(param_name_stream__.str());
    }
}; // model
}  // namespace
typedef model_plumstan_model_namespace::model_plumstan_model stan_model;
#endif
